"""accounting_tasks

Revision ID: 0c66617043bf
Revises: b73d173fe0c5
Create Date: 2023-08-20 16:02:04.532129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c66617043bf'
down_revision = 'b73d173fe0c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('accounting_tasks_pkey'))
    )
    op.create_index(op.f('accounting_tasks_id_idx'), 'accounting_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('accounting_tasks_id_idx'), table_name='accounting_tasks')
    op.drop_table('accounting_tasks')
    # ### end Alembic commands ###
