"""tasks

Revision ID: dcb7def1d453
Revises: 6dae4a6303aa
Create Date: 2023-08-13 00:09:57.058779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcb7def1d453"
down_revision = "6dae4a6303aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks_users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_users_pkey")),
    )
    op.create_index(op.f("tasks_users_id_idx"), "tasks_users", ["id"], unique=False)
    op.add_column("tasks", sa.Column("description", sa.String(), nullable=False))
    op.add_column("tasks", sa.Column("status", sa.String(), nullable=False))
    op.add_column("tasks", sa.Column("assigned_to", sa.String(), nullable=False))
    op.add_column("tasks", sa.Column("fee", sa.Integer(), nullable=False))
    op.add_column("tasks", sa.Column("reward", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "reward")
    op.drop_column("tasks", "fee")
    op.drop_column("tasks", "user_id")
    op.drop_column("tasks", "status")
    op.drop_column("tasks", "description")
    op.drop_index(op.f("tasks_users_id_idx"), table_name="tasks_users")
    op.drop_table("tasks_users")
    # ### end Alembic commands ###
