"""accounting_users

Revision ID: b73d173fe0c5
Revises: dcb7def1d453
Create Date: 2023-08-20 14:29:31.452193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73d173fe0c5'
down_revision = 'dcb7def1d453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('accounting_users_pkey'))
    )
    op.create_index(op.f('accounting_users_id_idx'), 'accounting_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('accounting_users_id_idx'), table_name='accounting_users')
    op.drop_table('accounting_users')
    # ### end Alembic commands ###
